#!/usr/bin/env sh

echo "Actually, that's a feature
I broke that deliberately to do some testing
I can't make that a priority right now
I can't test everything
I couldn't find any examples of how that can be done anywhere else in the project
I didn't anticipate that I would make any errors
I didn't create that part of the program
I forgot to commit the code that fixes that
I had to do the project backwards as people demanded results out of order
I haven't had any experience with that before
I have too many other high priority things to do right now
I heard there was a solar flare today
I'm not familiar with it so I didn't fix it in case I made it worse
I'm not getting any error codes
I must have been stress testing our production server
In the interest of efficiency I only check my email for that on a Friday
I thought I finished that
It must be a firewall issue
It must be because of a leap second
It must be because of a leap year
It's a browser compatibility issue
It's a character encoding issue
It's a known bug with the server software
It's always been like that
It's a remote vendor issue
It's never done that before
It works, but it's not been tested
It would take too long to rewrite the code from scratch
Management insisted we wouldn't need to waste our time writing unit tests
My time was split in a way that meant I couldn't do either project properly
Nobody asked me how long it would actually take
Nobody has ever complained about it
No one told me so I was forced to assume which way to do that
Oh, that was just a temporary fix
Oh, you said you DIDN'T want that to happen?
Our internet connection must not be working
Our redundant systems must have failed as well
Somebody must have changed my code
That code seemed so simple I didn't think it needed testing
That error means it was successful
That feature was slated for phase two
That feature would be outside of the scope
That important email must have been marked as spam
That's already fixed it just hasn't taken effect yet
That's the fault of the graphic designer
That was literally a one in a million error
That wasn't in the original specification
The accounting department must have cancelled that subscription
The client wanted it changed at the last minute
The existing design makes it difficult to do the right thing
The marketing department made us put that there
The original specification contained conflicting requirements
The person responsible doesn't work here anymore
The program has never collected that information
There must be something strange in your data
The request must have dropped some packets
There's currently a problem with our hosting company
There was too little data to bother with the extra functionality at the time
There were too many developers working on that same thing
The third party API is not responding
The third party documentation doesn't exist
The unit test doesn't cover that eventuality
The WYSIWYG must have produced an invalid output
THIS can't be the source of THAT
Well, at least it displays a very pretty error
Well at least we know not to try that again
Well, that's a first
We outsourced that months ago
We should have updated our software years ago
We spent three months debugging it because we only had one month to build it
What did I tell you about using parts of the system you don't understand?
What did you type in wrong to get it to crash?
Why do you want to do it that way?
You must be missing some of the dependencies
You must have the wrong version
Your browser must be caching the old content
You're doing it wrong" | shuf -n 1
